language: python
python:
- '3.4'
- '3.5'
- '3.6'
install:
- pip install -r requirements.txt
script:
- python manage.py test
deploy:
  provider: pypi
  twine_version: 1.12.1
  user: pdrum
  password:
    secure: r5tTW8BWH90yxlBQY+IeCBELB2u2K1Imya5auxBfW0HC3EQBA2OmRBm1+e7vhmq/wIe872nhXKUdRjsav/MmmvhE8dwSRzNreK/2K2An3y7psIk2+lvlBq/AZS02Nyb+pJ49KrC84lIuRCEQWpvmmAcR+7aw+ilsrvmT0WYHU0Kcd3dpbZwyAmV9jiXcVNtz2GFMbyyqxMJA/8OcFJw76CS+G2uR2T9kMUv9/wOmBz58F1Kf/fZb8FsDaKAjGi6QgQu9L3bNijx90cHZ5LwxEnhLIpYQ7O6T2qztJWi7fdZZjkLxbjNB+wAE3IHJ3UHRx1eRhybB5s4HLAjn8Nr/Ng+tLgryFaW+OBGC7tRUtLk0uC78d5M3RDhZ9KtWomqPcFMbc8BeZ+6AyXi617P5eAMIjjGisjCMQjZsmmIeB3q+8sIRl0mdodwaMsJ69i/2kgrQ4ayEPAxe72/R2mPXurUYxI5yWJBAb5YRFZ7ML0uzhzsW6ZnEBTGELF/bsftUJF1b29mo1q/cUIteXsrIwcbHtwWCPV5ziPsmtiXBZw4dZKg0TXHznxzve66Mh6m+Uee/Y1HjIZD5S6ZazgRZHv9Mj9qbcrvg0TBK4DY53qA9bVsDi5+wMrxZvdkSsCvoQr8FbtogyHpsOJ/c11OM7NjIAXMkQ7S1fcfGEcWTW2U=
  on:
    tags: true
