language: python
python:
- '3.4'
- '3.5'
- '3.6'
install:
- pip install -r requirements.txt
script:
- python manage.py test
deploy:
  provider: pypi
  twine_version: 1.12.1
  user: pdrum
  password:
    secure: OEcYYpVxGoZc+RvTdNwvfhqHDwonZ4knDVDrmvVyE4fB0Gj+AMhl5J2jtG/2N+H7fFDiXnXQVMyiPFIgUIPEva7GnpSXv8sim0n2Z7kgB8TPK/K7ZZSn43ozmHwT1oJKQhfJI32mM0LnTWqgHWNuCkpUq1gLJwgscJkEsYFj7JR+V39YSVpv7NMQQPh8VmrFnezFr96yymvd0euAVRk6aQ0TYuNdtfEkygKrCP63H0SFqtnwQiC17V9mtoo72vd1ZlvZUWcyAHiZuJ1ilwMx0wAI8jZxsGSmCTGUl9YMJDa8/gQWQBVohY9ijodhjLj64RD4d3u5vIBUJEZFBCGASAFsMHEnLUhLOQ1ic6j/ZzvwYo4LpfSfPTkx6pUzaJVtZqwCpCoxXxpSbjH4BW1ytGAkc1RzaYsrDUJMzPjNVBavGejhlkKYbLtLzmK2EWNzvKo9cm6D4atwGJxgvt+XZF2f6VDhrTKPG01v/+VVEzNj0g+azQaELtmTljtdL3PBXKcahMkWYJQb9VrFjFGjPgXmi4rRsJelRRXZetO0H9Kgt8zcbDb5D7B8An9AVTCRgj97dqtQATV61ATI+1EKcWOiD2Jyn3sZ0kMs8Vl83Z+cJlaeO7fTXjfqBvVJXvGPoBEgYggU6aahEYoQUbiUWasmxQxczbCzPwYnMW/X4jw=
  on:
    tags: true
