language: python
python:
- '3.4'
- '3.5'
- '3.6'
install:
- pip install -r requirements.txt
script:
- python manage.py test
deploy:
  provider: pypi
  twine_version: 1.12.1
  user: pdrum
  password:
    secure: bj5v3KXABqsoJMZdkV7FbZaN1gDLoIq3PiSyobC516U86IqqB+REmMiOn7SQ+cqbbLcPa/2KH7ri6Qp2nsdWKLt5KjkQ6NS17Ko/patvEy3uHMsSDB143F+gPftxtfVMeUOtdI0gCkzB8l66QCea+SSaQNKmqwk8Be/1UZGNMzxLZe5VE4qHA9BXbo2b5BnjLtDPgfsg8gUNFKp8llCssmViswOwxNF+jvDG0qUpkIBOch8juVweAaEgzXH/GX6X7z2s0NywVnVnviaRC+TPRitGNrIHBSmmZRohIR+j6jh4L2wtdhA1kXshLyKnLf9CAuzFYwiWB0lSo7B+abnMQyqkKlPNsSAbb/qmgBhrudRY5+5QQiD6NdQeSBOa0pnjOIUcUrcunr0kn1XlGSPml68ZVKIKwUM+OxfRupUeguwduYcKLFGzeoVPSKsnQLXl7ZxN7WRQrtwS6NlQTYhXUzj+CLhvkSTBFLiZ0Ja8uS+vyt95xdck+HWTh8L61Y3fU5VzWpKM0zICMqIvyMBdUGMP1esl9TPtVxF+JUoJMRL/OgxRDeo+cqvqUJHvKfpY0/tqq/UX6cMaDBel22/pwrgwu54nlo9E05drl/F7wRinC/incTEZECSl4rrkD82VIxzikk2St7/PVuo8m31DukLOOkyZ8KnF4HovRh8wfQc=
  on:
    tags: true
