language: python
python:
- '3.4'
- '3.5'
- '3.6'
install:
- pip install -r requirements.txt
script:
- python manage.py test
deploy:
  provider: pypi
  twine_version: 1.12.1
  user: pdrum
  password:
    secure: RSaTKIvA8BDQRoM8VsxADRrdb8otZQIiRcMa2od8XSAc9SImusdEPjen8iTER+AqIlib0G7JWD+NG1UcPWgo7BOd1PfElFP5vz3UJoDAbTmeTLf4PRcY/4zj6zx0oR9Ez46d0WX7CmgEp1MoBa5sRLeEdRjSANxKU1Y7kmUlJZBjjdlBgzpvaYP4Euy3ARmbBbCXAZLRRBRMeJfBDIlQK+0mU2f8qnBL4KXQUJoIJcqdC609fFtDymvlKTlf39sik2mBB4wtbZdVCJY+822krEqFAqNwubm9QJnlM4NX5yZvxgkAhjnZaO+OXI3vd95uDfBClXF5fuTLzvzyjSrVUwkuYtovV4lL8fJmhOH3BTobYTzjXzo4NZuEAVmDAAi9bYbhYgeoj4lJ8oY7BM1Q+rlJl25HTBJKar1V+6qYLpcFa2sbzwKza4Tceb8q0K58dQHIUCzsHf3FQoAsoJQ/OYZMpDr33qb4BhU20FJDZWAYoC5qtZgpf7OEfwyxpAuerzs359gP+UQp/8aYWehay06tsh+9JQztJj2NSYdJogqQl/Jy+1KbeUF+dsTK1voJgKVPpkY3yFHu7NC4ZqWEOh9NTZMirhIwastAoE/z0eKKyzZ0tOqAcXvIFx9SRdfG+pzLC9UgpdgTyggtVZGJlpQ3H/XUj79znkiUQ9vDdkg=
  on:
    tags: true
